//! YouTube scrape command implementation.

use std::io::IsTerminal;

use serde_json::{Value, json};

use crate::account;
use crate::cli::ScrapeArgs;
use crate::error::Result;
use crate::output;

pub fn run(args: ScrapeArgs) -> Result<()> {
    let resolved = account::resolve(args.account.as_deref(), args.api_key.as_deref())?;
    let client = resolved.client();

    if std::io::stderr().is_terminal() {
        eprintln!("Scraping YouTube (this may take 30–60s)...");
    }

    let mut body = serde_json::Map::new();
    body.insert("startUrls".into(), json!([{"url": args.url}]));
    body.insert("maxResults".into(), json!(args.max_results));
    body.insert("maxResultsShorts".into(), json!(args.max_shorts));
    body.insert("maxResultStreams".into(), json!(args.max_streams));

    if let Some(sort) = args.sort {
        body.insert("sortVideosBy".into(), json!(sort));
    }
    if args.download_subs {
        body.insert("downloadSubtitles".into(), json!(true));
        body.insert("subtitlesLanguage".into(), json!(args.subs_lang));
        body.insert("subtitlesFormat".into(), json!(args.subs_format));
    }
    if args.auto_subs {
        body.insert("preferAutoGeneratedSubtitles".into(), json!(true));
    }
    if let Some(since) = args.since {
        body.insert("oldestPostDate".into(), json!(since));
    }

    let res = client.post("acts/streamers~youtube-scraper/run-sync-get-dataset-items", &Value::Object(body))?;
    output::write(&res);
    Ok(())
}
