using System.ComponentModel;
using Youtube.Console.Infrastructure;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Youtube.Console.Commands;

public sealed class ScrapeCommand : AsyncCommand<ScrapeCommand.Settings>
{
    public sealed class Settings : GlobalSettings
    {
        [CommandArgument(0, "<URL>")]
        [Description("YouTube URL (video, channel, playlist, hashtag, or search results page)")]
        public required string Url { get; init; }

        [CommandOption("--max-results <N>")]
        [Description("Maximum regular videos (0 = unlimited)")]
        [DefaultValue(10)]
        public int MaxResults { get; init; } = 10;

        [CommandOption("--max-shorts <N>")]
        [Description("Maximum Shorts to return")]
        [DefaultValue(0)]
        public int MaxShorts { get; init; }

        [CommandOption("--max-streams <N>")]
        [Description("Maximum streams to return")]
        [DefaultValue(0)]
        public int MaxStreams { get; init; }

        [CommandOption("--sort <ORDER>")]
        [Description("Sort channel videos by: NEWEST, POPULAR, OLDEST")]
        public string? Sort { get; init; }

        [CommandOption("--download-subs")]
        [Description("Download subtitles")]
        public bool DownloadSubs { get; init; }

        [CommandOption("--subs-lang <LANG>")]
        [Description("Subtitle language: any, en, de, es, fr, it, ja, ko, nl, pt, ru")]
        [DefaultValue("en")]
        public string SubsLang { get; init; } = "en";

        [CommandOption("--subs-format <FMT>")]
        [Description("Subtitle format: srt, vtt, xml, plaintext")]
        [DefaultValue("srt")]
        public string SubsFormat { get; init; } = "srt";

        [CommandOption("--auto-subs")]
        [Description("Prefer auto-generated subtitles")]
        public bool AutoSubs { get; init; }

        [CommandOption("--since <DATE>")]
        [Description("Only videos published after this date (e.g. 2025-01-01 or '7 days')")]
        public string? Since { get; init; }
    }

    protected override async Task<int> ExecuteAsync(CommandContext context, Settings settings, CancellationToken cancellation)
    {
        AnsiConsole.MarkupLine("[grey]Scraping YouTube (this may take 30–60s)...[/]");

        using var client = settings.CreateClient();
        var doc = await client.RunAsync(new
        {
            startUrls = new[] { new { url = settings.Url } },
            maxResults = settings.MaxResults,
            maxResultsShorts = settings.MaxShorts,
            maxResultStreams = settings.MaxStreams,
            sortVideosBy = settings.Sort,
            downloadSubtitles = settings.DownloadSubs ? true : (bool?)null,
            subtitlesLanguage = settings.DownloadSubs ? settings.SubsLang : null,
            subtitlesFormat = settings.DownloadSubs ? settings.SubsFormat : null,
            preferAutoGeneratedSubtitles = settings.AutoSubs ? true : (bool?)null,
            oldestPostDate = settings.Since
        });

        YamlOutput.Write(doc);
        return 0;
    }
}
