//! YouTube search command implementation.

use std::io::IsTerminal;

use serde_json::{Value, json};

use crate::account;
use crate::cli::SearchArgs;
use crate::error::Result;
use crate::output;

pub fn run(args: SearchArgs) -> Result<()> {
    let resolved = account::resolve(args.account.as_deref(), args.api_key.as_deref())?;
    let client = resolved.client();

    if std::io::stderr().is_terminal() {
        eprintln!("Searching YouTube (this may take 30–60s)...");
    }

    let mut body = serde_json::Map::new();
    body.insert("searchQueries".into(), json!([args.query]));
    body.insert("maxResults".into(), json!(args.max_results));
    body.insert("maxResultsShorts".into(), json!(args.max_shorts));
    body.insert("maxResultStreams".into(), json!(args.max_streams));

    if let Some(sort) = args.sort {
        body.insert("sortingOrder".into(), json!(sort));
    }
    if let Some(date) = args.date {
        body.insert("dateFilter".into(), json!(date));
    }
    if let Some(length) = args.length {
        body.insert("lengthFilter".into(), json!(length));
    }
    if let Some(vtype) = args.video_type {
        body.insert("videoType".into(), json!(vtype));
    }
    if args.hd {
        body.insert("isHD".into(), json!(true));
    }
    if args.live {
        body.insert("isLive".into(), json!(true));
    }
    if args.four_k {
        body.insert("is4K".into(), json!(true));
    }
    if args.subtitles {
        body.insert("hasSubtitles".into(), json!(true));
    }
    if args.cc {
        body.insert("hasCC".into(), json!(true));
    }
    if args.download_subs {
        body.insert("downloadSubtitles".into(), json!(true));
        body.insert("subtitlesLanguage".into(), json!(args.subs_lang));
        body.insert("subtitlesFormat".into(), json!(args.subs_format));
    }
    if args.auto_subs {
        body.insert("preferAutoGeneratedSubtitles".into(), json!(true));
    }
    if let Some(since) = args.since {
        body.insert("oldestPostDate".into(), json!(since));
    }

    let res = client.post("acts/streamers~youtube-scraper/run-sync-get-dataset-items", &Value::Object(body))?;
    output::write(&res);
    Ok(())
}
