using System.ComponentModel;
using Youtube.Console.Infrastructure;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Youtube.Console.Commands;

public sealed class SearchCommand : AsyncCommand<SearchCommand.Settings>
{
    public sealed class Settings : GlobalSettings
    {
        [CommandArgument(0, "<QUERY>")]
        [Description("Search query")]
        public required string Query { get; init; }

        [CommandOption("--max-results <N>")]
        [Description("Maximum videos to return (0 = unlimited)")]
        [DefaultValue(10)]
        public int MaxResults { get; init; } = 10;

        [CommandOption("--max-shorts <N>")]
        [Description("Maximum Shorts to return")]
        [DefaultValue(0)]
        public int MaxShorts { get; init; }

        [CommandOption("--max-streams <N>")]
        [Description("Maximum streams to return")]
        [DefaultValue(0)]
        public int MaxStreams { get; init; }

        [CommandOption("--sort <ORDER>")]
        [Description("Sort by: relevance, rating, date, views")]
        public string? Sort { get; init; }

        [CommandOption("--date <FILTER>")]
        [Description("Upload date filter: hour, today, week, month, year")]
        public string? Date { get; init; }

        [CommandOption("--length <FILTER>")]
        [Description("Length filter: under4, between420, plus20")]
        public string? Length { get; init; }

        [CommandOption("--type <TYPE>")]
        [Description("Video type: video, movie")]
        public string? Type { get; init; }

        [CommandOption("--hd")]
        [Description("Only HD videos")]
        public bool Hd { get; init; }

        [CommandOption("--live")]
        [Description("Only live videos")]
        public bool Live { get; init; }

        [CommandOption("--four-k")]
        [Description("Only 4K videos")]
        public bool Is4K { get; init; }

        [CommandOption("--subtitles")]
        [Description("Only videos with subtitles/CC")]
        public bool Subtitles { get; init; }

        [CommandOption("--cc")]
        [Description("Only Creative Commons videos")]
        public bool CreativeCommons { get; init; }

        [CommandOption("--download-subs")]
        [Description("Download subtitles")]
        public bool DownloadSubs { get; init; }

        [CommandOption("--subs-lang <LANG>")]
        [Description("Subtitle language: any, en, de, es, fr, it, ja, ko, nl, pt, ru")]
        [DefaultValue("en")]
        public string SubsLang { get; init; } = "en";

        [CommandOption("--subs-format <FMT>")]
        [Description("Subtitle format: srt, vtt, xml, plaintext")]
        [DefaultValue("srt")]
        public string SubsFormat { get; init; } = "srt";

        [CommandOption("--auto-subs")]
        [Description("Prefer auto-generated subtitles")]
        public bool AutoSubs { get; init; }

        [CommandOption("--since <DATE>")]
        [Description("Only videos published after this date (e.g. 2025-01-01 or '7 days')")]
        public string? Since { get; init; }
    }

    protected override async Task<int> ExecuteAsync(CommandContext context, Settings settings, CancellationToken cancellation)
    {
        AnsiConsole.MarkupLine("[grey]Searching YouTube (this may take 30–60s)...[/]");

        using var client = settings.CreateClient();
        var doc = await client.RunAsync(new
        {
            searchQueries = new[] { settings.Query },
            maxResults = settings.MaxResults,
            maxResultsShorts = settings.MaxShorts,
            maxResultStreams = settings.MaxStreams,
            sortingOrder = settings.Sort,
            dateFilter = settings.Date,
            lengthFilter = settings.Length,
            videoType = settings.Type,
            isHD = settings.Hd ? true : (bool?)null,
            isLive = settings.Live ? true : (bool?)null,
            is4K = settings.Is4K ? true : (bool?)null,
            hasSubtitles = settings.Subtitles ? true : (bool?)null,
            hasCC = settings.CreativeCommons ? true : (bool?)null,
            downloadSubtitles = settings.DownloadSubs ? true : (bool?)null,
            subtitlesLanguage = settings.DownloadSubs ? settings.SubsLang : null,
            subtitlesFormat = settings.DownloadSubs ? settings.SubsFormat : null,
            preferAutoGeneratedSubtitles = settings.AutoSubs ? true : (bool?)null,
            oldestPostDate = settings.Since
        });

        YamlOutput.Write(doc);
        return 0;
    }
}
